# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hot_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_url', models.URLField()),
                ('publish_time', models.DateTimeField()),
                ('repoter', models.CharField(max_length=30)),
                ('headline', models.CharField(max_length=70, unique=True)),
                ('content', models.TextField()),
                ('img_dir', models.CharField(max_length=50)),
                ('video_dir', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Hot_News',
            },
        ),
    ]
